### ISSUE TITLE
Windows Defencer SmartScreen

### ISSUE THREAD

**Issue by Woologic** [Ravbug/MCSoundsExtractorCPP#3]
Windows is trying to protect my PC, I know I can run it by ignoring this, but is this application 100% safe? I've downloaded a virus before and I had to wipe my entire PC, I just wanna make sure I'm safe.

**Comment by Ravbug** [comment]
SmartScreen triggers because it's not codesigned, because that costs money. If you're concerned about the precompiled downloads, you can read the source code yourself and compile your own copy.
